namespace MineCraftUnity.World
{
    /// <summary>
    /// MC ref: net.minecraft.world.level.biome.Biomes — overworld multi-noise subset.
    /// </summary>
    public enum BiomeId : byte
    {
        Unknown = 0,
        MushroomFields = 1,
        DeepFrozenOcean = 2,
        DeepColdOcean = 3,
        DeepOcean = 4,
        DeepLukewarmOcean = 5,
        DeepWarmOcean = 6,
        FrozenOcean = 7,
        ColdOcean = 8,
        Ocean = 9,
        LukewarmOcean = 10,
        WarmOcean = 11,
        StonyShore = 12,
        Beach = 13,
        SnowyBeach = 14,
        Swamp = 15,
        MangroveSwamp = 16,
        SnowyPlains = 17,
        IceSpikes = 18,
        SnowyTaiga = 19,
        Plains = 20,
        SunflowerPlains = 21,
        Forest = 22,
        FlowerForest = 23,
        BirchForest = 24,
        OldGrowthBirchForest = 25,
        DarkForest = 26,
        Taiga = 27,
        OldGrowthSpruceTaiga = 28,
        OldGrowthPineTaiga = 29,
        Meadow = 30,
        CherryGrove = 31,
        Savanna = 32,
        SavannaPlateau = 33,
        WindsweptSavanna = 34,
        Jungle = 35,
        SparseJungle = 36,
        BambooJungle = 37,
        Desert = 38,
        Badlands = 39,
        ErodedBadlands = 40,
        WoodedBadlands = 41,
        SnowySlopes = 42,
        Grove = 43,
        JaggedPeaks = 44,
        FrozenPeaks = 45,
        StonyPeaks = 46,
        WindsweptHills = 47,
        WindsweptGravellyHills = 48,
        WindsweptForest = 49,
        PaleGarden = 50,
        River = 51
    }
}
